### ISSUE TITLE
Slurm terminology for job status

### ISSUE THREAD

**Issue by sdebanks** [SANBI-SA/user_documentation#26]
I used this page to find out definitions of job status abbreviations 
https://slurm.schedmd.com/squeue.html

Hopefully it is accurate!

**Comment by Banshee1221** [comment]
Thanks for the suggestion. I've added some information to the page here: https://docs.sanbi.ac.za/#/cluster/running_jobs?id=executing-and-managing-jobs

This was solved by commit: 08ee8a8
